### ISSUE TITLE
Tracking issue for Release artefacts and notes for G release

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/soda#7]
**Issue/Feature Description:**
Track all:

- [x] Release notes

- [x] Release binary upload

- [x] Release documents for installation and usage guide updated

- [x] Sanity of the release on all supported platform, as per the release notes

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
Closing as the artifacts were uploaded for G release
